# Use an official node runtime as a parent image
FROM node:10.13.0-slim

# Set the working directory to /app
WORKDIR /app

# APT packages
RUN apt-get -qq update
RUN apt-get -qq install libgconf-2-4

# NPM packages
ADD ./package.json    /app
RUN npm i

# Project files
ADD ./dist/index.html /app
ADD ./dist/index.js   /app
ADD ./server.js       /app
ADD ./admin.js        /app
DD ./start.sh        /app

# entry script
RUN chmod +x start.sh

# Make ports available to the world outside this container
EXPOSE 80
EXPOSE 8080

# Run app when the container launches
CMD ["./start.sh"]
